# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  S3_BUCKET_NAME: jys3
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
      
      ## create application-test.yml
    - name: make application.yml
      run:
        echo "${{ secrets.PROPERTIES_TEST }}" > ./src/main/resources/application.yml
      shell: bash

      ## create application-prod.yml
    - name: make application-prod.yml
      run:
        echo "${{ secrets.PROPERTIES_PROD }}" > ./src/main/resources/application-prod.yml
      shell: bash
      
      ## create fcm.json
    - name: fcm create-json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "togather-a5d1a-firebase-adminsdk-hg2ul-2e9db00894.json"
        json: ${{ secrets.FCM_SECRET }}
        dir: '/src/main/resources/'
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        
    - name: Make zip file
      run: zip -r ./togather-jar.zip .
      shell: bash
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_JYS }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_JYS }}
        aws-region: ap-northeast-2
      
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./togather-jar.zip s3://$S3_BUCKET_NAME/togather-jar.zip
      
    - name: Code Deploy
      run: >
        aws deploy create-deployment --application-name jys-aws-code-deploy
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name jys-aws-code-deploy-group
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=togather-jar.zip
